---
# tasks file for apache
- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Start Apache service
  systemd:
    name: apache2
    state: started

- name: Copy index.html to web servers
  copy:
    src: index.html
    dest: /var/www/html/index.html

